### ISSUE TITLE
New packages for deployer

### ISSUE THREAD

**Issue by pbkeating** [reconhub/deployer#25]
Hi @zkamvar ,

Need to do some fuzzy searching at the moment and found the [fuzzyjoin package.](https://cran.r-project.org/web/packages/fuzzyjoin/index.html)
Would it be possible to add it to the deployer, or are there other fuzzy join packages that you would recommend?

Thanks,
Patrick

**Comment by zkamvar** [comment]
Hi @pbkeating, I think that's a good addition to the deployer. It's written by a prominent member of the R community, has continuous integration, and has 91% tests, so I'm cool with this. 

I aim to have the new packages added to the deployer and the new version released in the next couple of weeks.

**Comment by pbkeating** [comment]
Just starting using the `daff` package for comparing datasets. I think it's very good and has an easy to use output. Could be a worthwhile addition.

**Comment by zkamvar** [comment]
I also like this suggestion. `daff` seems to solve the same problem that `linelist::compare_data()` attempts to do, but with a lot more features!

I'm going to open a new "package requests" issue for this that will always stay open.

A side note: in general, it's not a good idea to request new features on an old issue, because it's harder to track.
