### ISSUE TITLE
KableExtra, FlexTable, and Zip

### ISSUE THREAD

**Issue by Adismer7** [reconhub/deployer#26]
Hi all,

I want to make nicer tables for presentations with FlexTable and KableExtra. These are not compatible with the R 3.5.2. Also the zip package is 1.0 whereas the dependency for KableExtra is 2.0.

Can you please add these to the deployer? Also let me know if there are any better options for table making now in deployer.

Thanks!
AD

**Comment by zkamvar** [comment]
> I want to make nicer tables for presentations with FlexTable and KableExtra. These are not compatible with the R 3.5.2. 

We can certainly add the *flextable* and *kableExtra* packages to the deployer. I'm not sure why you say they are not compatible with R 3.5.2 since kableExtra explicitly says it works with a minimum version of 3.1.0. Besides, the most recent release of the deployer should have R 3.5.3 available. 

> Also the zip package is 1.0 whereas the dependency for KableExtra is 2.0.

I think you may have an older version of deployer. The current deployer release is from 2019-03-25: https://github.com/reconhub/deployer/releases/tag/20190325 

I think this may be a documentation omission on our part. We will be working in the next few weeks to improve the deployer architecture and iron out the bugs in the documentation.
