### ISSUE TITLE
update_package fails

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/deployer#31]
Using the deployer from `deployer_2019_05_13`, and a recent update (9bdc92d71e46) of the git repos of `earlyR` (an outdated version is on the deployer), I get:

```
> update_package("~/dev/recon/earlyR/")
Building source package ...
✔  checking for file ‘/home/master/dev/recon/earlyR/DESCRIPTION’ ...
─  preparing ‘earlyR’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘earlyR_0.0.1.tar.gz’
   
Adding source package and to .
Error in file.exists(file) : invalid 'file' argument
> getwd()
[1] "/home/master/deployers/deployer_2019_05_13"
> traceback()
3: file.exists(file)
2: drat::insertPackage(src, action = "archive", repodir = repo) at update_deployer.R#51
1: update_package("~/dev/recon/earlyR/")
```

Incidentally, it would be best to rename the `.R` file so that it matches the function's name.

**Comment by zkamvar** [comment]
For clarity, you are referring to this commit from earlyR? https://github.com/reconhub/earlyR/commit/9bdc92d71e46d867f09dd0916c31360e66448a56

I suspect it's failing to install because the master branch of EpiEstim (which earlyR depends on) is horribly out of date and people have moved on using the release branch (or so I suspect), but the deployer only installs the master branch. IIRC, this is part of the reason why I never made the PR for that earlyR commit, because I could never get it to work in the first place. 

There's also the issue that the update_package function explicitly does not check for dependencies when installing (as per the remit: #18), so that may come into play.

That being said, I'll check into these things when I get in tomorrow. Can you copy/paste the version you have for EpiEstim?

**Comment by zkamvar** [comment]
A bit of an update:

 - correct version of EpiEstim has been identified for earlyR and PR has been initiated: https://github.com/reconhub/earlyR/pull/9
 - Reconciliation of EpiEstim branches imminent: https://github.com/annecori/EpiEstim/issues/63
 - I've put in a request for coarseDataTools to update: https://github.com/nickreich/coarseDataTools/issues/49

**Comment by thibautjombart** [comment]
Hi there, 
this issue is pointing its ugly mug again, this time with a different package:
```r
> update_package(pkg = "~/dev/recon/reportfactory/")
Building source package ...
✔  checking for file ‘/home/master/dev/recon/reportfactory/DESCRIPTION’
─  preparing ‘reportfactory’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘reportfactory_0.0.4.tar.gz’
   
Adding source package and to .
Error in file.exists(file) : invalid 'file' argument
> traceback()
3: file.exists(file)
2: drat::insertPackage(src, action = "archive", repodir = repo) at update_deployer.R#52
1: update_package(pkg = "~/dev/recon/reportfactory/")
> 
```
